# override things in parent directories config.toml (remove this once the option to not use configs in parent directories exists)
[build]
target = "x86_64-unknown-linux-gnu"

# Future - necessary for the experimental "native build" of esp-idf-sys with ESP32C3
# See also https://github.com/ivmarkov/embuild/issues/16
rustflags = []

[unstable]
# see https://github.com/rust-lang/cargo/issues/8733
build-std = []
#build-std-features = ["panic_immediate_abort"] # Only necessary if building against ESP-IDF tag `v4.3.2` (the minimum supported version)


