[package]
name = "squirrel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.3.3"
num_enum = "0.6.0"
serde = { version = "1.0.152", features = ["derive"] }
static_assertions = "1.1.0"
zerocopy = "0.6.1"
uuid = { version = "1.3.1", features = ["v4", "serde"] }
smol = { version = "1.2.5", optional = true }
log = { version = "0.4", optional = true }
tokio = { version = "1.27.0", optional = true, features = ["net", "time", "macros"] }
tracing = { version = "0.1", optional = true }
async-trait = "0.1.68"

[features]
server-utils = []
tokio = ["dep:tokio", "dep:tracing"]
smol = ["dep:smol", "dep:log"]


